title: Pat Stewart
email: sarateofilova@gmail.com
description: Pat Stewart, musician, bass player, music producer, beatmaker
destination: docs
baseurl: ""
# baseurl: "/Pat-Stewart"
url: "http://sarateofilova.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sarateofilova
github_username:  sarateofilova

exclude: [node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md]
# Build settings
# markdown: kramdown
# plugins:
#   - jekyll-feed
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

